### ISSUE TITLE
provide an API that will return inactive pledges

### ISSUE THREAD

**Issue by balupton** [Patreon/patreon-js#12]
it is unfortunate that the API only provides active pledges, one of our patrons supported us for 8 months in 2016, but his details are no longer returned via the API endpoints.

I was able to grab his details manually from https://www.patreon.com/manageRewards - however it would be awesome if there was an API for this, as manually it would be untenable to do with hundreds of inactive patrons

the use case for this will be to:

1. be able to identify via a program the total donated amount of a user, even if they have inactive pledges
2. optional: be able to identify via a program how much a user gave during a month that had a past pledge

**Comment by spencerhandley** [comment]
Hey @balupton, this will be considered for later versions of the API. It's something we'd really like to do in the future.

**Comment by balupton** [comment]
did this land?
