### ISSUE TITLE
Not a issue just a question.

### ISSUE THREAD

**Issue by TheTeaCup** [Patreon/patreon-js#31]
With this am i able to get the recent patreons that sub to my content?
Like if i have a new user to sub to my patreon can i use this api to get there info like naw and pledge to send to my discord bot?

**Comment by skeddles** [comment]
Are you aware patreon has discord integration that can automatically assign roles to authenticated patrons?

**Comment by Pukimaa** [comment]
I gues they are but for example I am looking for a way to do stuff in my Discord bot when someone gets a Patron.
So if someone is support the patreon of the bot I'll add their Discord ID to an array in node.js I can use for my discord bot
