### ISSUE TITLE
api is incorrect

### ISSUE THREAD

**Issue by balupton** [Patreon/patreon-js#4]
actual API is:

```
const patreon = require('patreon').default
const oauth = require('patreon').oauth
```

as a side note, considering this is only going to be on node.js, and considering node.js may never support es modules, using es modules on node is a bit of a waste of time, something like https://github.com/bevry/editions can be used instead for having the future today while having backwards compatibility support

**Comment by 21echoes** [comment]
Awesome! We'll update the readme accordingly
